### ISSUE TITLE
Code not compiling 

### ISSUE THREAD

**Issue by Aaryansh7** [jviquerat/drl_shape_optimization#2]
After following all the steps as specified in the readme, I am getting the following error(in the execution of - " python3 launch_parallel_training.py -p 1111 -n 4") - 

```
WARNING:tensorflow:From /home/aaryansh/.local/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py:1659: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
2022-01-21 15:26:15.508561: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ros/noetic/lib:/opt/ros/noetic/lib/x86_64-linux-gnu:/home/aaryansh/.mujoco/mujoco210/bin
2022-01-21 15:26:15.508595: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
2022-01-21 15:26:15.508619: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (aaryansh-ThinkPad-E14): /proc/driver/nvidia/version does not exist
Traceback (most recent call last):
  File "launch_parallel_training.py", line 91, in <module>
    runner = ParallelRunner(agent=agent, environments=remote_envs)
  File "/home/aaryansh/Documents/RL_fluids_papers/drl_shape_optim/drl_shape_optimization/src/tensorforce/tensorforce/execution/parallel_runner.py", line 48, in __init__
    self.agent.initialize()
  File "/home/aaryansh/Documents/RL_fluids_papers/drl_shape_optim/drl_shape_optimization/src/tensorforce/tensorforce/agents/agent.py", line 151, in initialize
    self.model.setup()  # should be self.model.initialize()
  File "/home/aaryansh/Documents/RL_fluids_papers/drl_shape_optim/drl_shape_optimization/src/tensorforce/tensorforce/core/models/model.py", line 354, in setup
    self.initialize()
  File "/home/aaryansh/Documents/RL_fluids_papers/drl_shape_optim/drl_shape_optimization/src/tensorforce/tensorforce/core/module.py", line 320, in initialize
    function = self.create_api_function(
  File "/home/aaryansh/Documents/RL_fluids_papers/drl_shape_optim/drl_shape_optimization/src/tensorforce/tensorforce/core/module.py", line 358, in create_api_function
    results = api_function()
  File "/home/aaryansh/Documents/RL_fluids_papers/drl_shape_optim/drl_shape_optimization/src/tensorforce/tensorforce/core/models/model.py", line 832, in api_act
    with tf.control_dependencies(control_inputs=assertions):
  File "/home/aaryansh/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 5173, in control_dependencies
    return get_default_graph().control_dependencies(control_inputs)
  File "/home/aaryansh/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 4591, in control_dependencies
    c = self.as_graph_element(c)
  File "/home/aaryansh/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3512, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/aaryansh/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3600, in _as_graph_element_locked
    raise TypeError("Can not convert a %s into a %s." %
TypeError: Can not convert a NoneType into a Tensor or Operation.
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'ppo.act/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/aaryansh/Documents/RL_fluids_papers/drl_shape_optim/drl_shape_optimization/src/tensorforce/tensorforce/core/models/model.py", line 832, in api_act
    with tf.control_dependencies(control_inputs=assertions):  File "/home/aaryansh/.local/lib/python3.8/site-packages/tensorflow/python/ops/check_ops.py", line 873, in assert_less_v2
    return assert_less(x=x, y=y, summarize=summarize, message=message, name=name)  File "/home/aaryansh/.local/lib/python3.8/site-packages/tensorflow/python/ops/check_ops.py", line 879, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/aaryansh/.local/lib/python3.8/site-packages/tensorflow/python/ops/check_ops.py", line 372, in _binary_assert
    return control_flow_ops.Assert(condition, data, summarize=summarize)  File "/home/aaryansh/.local/lib/python3.8/site-packages/tensorflow/python/util/tf_should_use.py", line 235, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'ppo.act/assert_non_negative/assert_less_equal/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/aaryansh/.local/lib/python3.8/site-packages/tensorflow/python/ops/check_ops.py", line 539, in assert_non_negative_v2
    return assert_non_negative(x=x, summarize=summarize, message=message,  File "/home/aaryansh/.local/lib/python3.8/site-packages/tensorflow/python/ops/check_ops.py", line 560, in assert_non_negative
    return assert_less_equal(zero, x, data=data, summarize=summarize)  File "/home/aaryansh/.local/lib/python3.8/site-packages/tensorflow/python/ops/check_ops.py", line 923, in assert_less_equal
    return _binary_assert('<=', 'assert_less_equal', math_ops.less_equal,  File "/home/aaryansh/.local/lib/python3.8/site-packages/tensorflow/python/ops/check_ops.py", line 372, in _binary_assert
    return control_flow_ops.Assert(condition, data, summarize=summarize)  File "/home/aaryansh/.local/lib/python3.8/site-packages/tensorflow/python/util/tf_should_use.py", line 235, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
```

Please provide possible solutions or let me know if there is a compatibility/version issue with the code.

**Comment by jviquerat** [comment]
Hi,

Are you using the suggested docker container ?

**Comment by Aaryansh7** [comment]
No, I have manually installed the required packages, i-e method1. But from the error, it does not seem that there is an issue with the required packages or installation.

**Comment by jviquerat** [comment]
As the `requirements.txt` does not enforce any specific version of the packages, it is likely that recent versions of these packages are no more compatible with this project (I'm confident that `meshio`, among others, does not provide backward compatibility). I encourage you to use the provided docker container.
Unfortunately I don't have any time available to provide backup on this project.

If you're interested in the optimization process more than in the shape optimization matter, you could be interested in this other project, which implements a much more efficient version of the method : https://github.com/jviquerat/pbo

Best

**Comment by Aaryansh7** [comment]
Thank You
